version: '3'
services:
  sql:
    image: mcr.microsoft.com/azure-sql-edge
    environment:
      - ACCEPT_EULA=1
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
      - MSSQL_PID=Developer
      - MSSQL_USER=SA
    ports:
      - "1433:1433"
    container_name: "SQLServer"
    restart: unless-stopped